// Generated by CoffeeScript 1.7.1
(function() {
  define(["module"], function(module) {
    var hasLocation, magic, masterConfig, theFiles;
    hasLocation = typeof location !== "undefined" && location.href;
    masterConfig = (module.config && module.config()) || {};
    theFiles = [];
    magic = {
      load: function(name, req, onLoad, config) {
        var doIt, fs, path;
        fs = require.nodeRequire("fs");
        path = require.nodeRequire("path");
        doIt = function(dir) {
          var f, files, fullPath, magicFile, mf, moduleId, stats, _i, _len, _results;
          files = fs.readdirSync(dir);
          _results = [];
          for (_i = 0, _len = files.length; _i < _len; _i++) {
            f = files[_i];
            fullPath = path.resolve(dir, f);
            stats = fs.statSync(fullPath);
            if (stats.isDirectory()) {
              _results.push(doIt(fullPath));
            } else if (f === "magic.json") {
              magicFile = JSON.parse(fs.readFileSync(fullPath, 'UTF-8'));
              if (magicFile[name] != null) {
                _results.push((function() {
                  var _j, _len1, _ref, _results1;
                  _ref = magicFile[name];
                  _results1 = [];
                  for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
                    mf = _ref[_j];
                    moduleId = path.relative(config.dirBaseUrl, path.resolve(dir, mf));
                    req([moduleId]);
                    _results1.push(theFiles.push("'" + moduleId + "'"));
                  }
                  return _results1;
                })());
              } else {
                _results.push(void 0);
              }
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        };
        doIt(req.toUrl(config.dirBaseUrl));
        console.log(theFiles);
        onLoad();
      },
      write: function(pluginName, moduleName, write) {
        var str;
        str = "define('" + pluginName + "!" + moduleName + "', [";
        str += theFiles.join(',');
        str += "], function() { return arguments; });";
        write(str);
      }
    };
    return magic;
  });

}).call(this);
